### ISSUE TITLE
Getting new report throws an error

### ISSUE THREAD

**Issue by al3xVR** [Ataraxxia/godin#5]
My server throws the error message "godin.go:108 main.uploadReport () EOF" as soon as it receives the JSON file.
The client is an Ubuntu Desktop "21.04 (Hirsute Hippo)".
I have tried with a smaller JSON file, but the same error.
Here you see the JSON file from the client:

root@lnx221-0187:/usr/bin# cat /tmp/godin_payload
{
"host_info" : {
	"kernel": "5.11.0-38-generic",
	"architecture": "x86_64",
	"os": "Ubuntu 21.04",
	"hostname": "lnx221-0187"
},
"tags" : [],
"protocol" : "1",
"repo_type" : "deb",
"package_manager" : "apt",
"packages" : [
{
	"name": "accountsservice",
	"version": "0.6.55-0ubuntu13.2",
	"architecture": "amd64",
	"repository": "http://de.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages"
},
{
	"name": "acl",
	"version": "2.2.53-10ubuntu1",
	"architecture": "amd64",
	"repository": "http://de.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages"
},
{
	"name": "acpi-support",
	"version": "0.143",
	"architecture": "amd64",
	"repository": "http://de.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages"
},
{
	"name": "acpid",
	"version": "1:2.0.32-1ubuntu1",
	"architecture": "amd64",
	"repository": "http://de.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages"
}
]
}

**Comment by Ataraxxia** [comment]
Thank you for your report. What version are you using? Initial release? If possible please check out with latest v1.1 release. It might require manual conversion of database columns.

**Comment by al3xVR** [comment]
Hello, thanks for your response. There we use the version from the main Branches. I don't really know which version is that.

**Comment by F0rk-b0mb** [comment]
@Ataraxxia 

Hi, I still got the same error. I used Version 1.1.

`
...
+ cat /tmp/godin_host_info
+ echo ,
+ echo -n '"tags" : ['
+ '[' '!' -z '' ']'
+ echo '],'
+ echo '"protocol" : "1",'
+ '[' -s /tmp/godin_repo_info ']'
+ cat /tmp/godin_pkg_list
+ echo '}'
+ curl -L -X POST -H 'Content-Type: application/json' -d @/tmp/godin_payload http://xxx.xxx.xxx.xxx:8080/reports/upload
Godin says Json decoding error
+ cleanup
+ rm /tmp/godin_host_info
+ rm /tmp/godin_pkg_list
+ '[' -s /tmp/godin_repo_info ']'
+ rm /tmp/godin_payload`

`INFO[0000] Starting server xxx.xxx.xxx.xxx:8080            
ERRO[0280] EOF                                          
ERRO[0402] EOF `

**Comment by Ataraxxia** [comment]
Thank you all for the reports, the fixes are now included in the main branch

**Comment by al3xVR** [comment]
Hello, now it works perfect! Thank you for your quick solution. Have a good time.
